language: ruby
cache: bundler
sudo: false
matrix:
  fast_finish: true
  include:
    - rvm: 2.2.3
    - rvm: 2.3.0

notifications:
  email: false
bundler_args: --jobs=3 --retry=3 --without development devops 
